
CREATE TABLE G_SERVICES (
	"FIELDS" VARCHAR(4000) NOT NULL, 
	"KEYS" VARCHAR(400) NOT NULL, 
	"SEPARATOR" VARCHAR(400), 
	"TABLE_NAME" VARCHAR(400) NOT NULL, 
	"SELECT_VALUE" VARCHAR(4000), 
	"RESOLVER" VARCHAR(400), 
	"FINAL_TABLE" VARCHAR(400), 
	"TYPE" VARCHAR(400), 
	"SEC_RESOLVER" VARCHAR(400), 
	"SEC_INFO" VARCHAR(4000), 
	"SELECT_FILTER" VARCHAR(4000), 
	"INSERT_VALUE" VARCHAR(4000), 
	"UPDATE_VALUE" VARCHAR(4000), 
	"DELETE_VALUE" VARCHAR(4000) 
   );


CREATE TABLE EMP (
	"ID" VARCHAR(20) NOT NULL, 
	"NAME" VARCHAR(400) NOT NULL, 
	"ID_DEP" VARCHAR(20) NOT NULL 
   );

CREATE TABLE DEP (
	"ID" VARCHAR(20) NOT NULL, 
	"NAME" VARCHAR(400) NOT NULL, 
   );
   